# Generated by Django 6.0.2 on 2026-02-17 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='media/company_pics/')),
                ('company_name', models.CharField(max_length=20, unique=True)),
                ('company_location', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_choices', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('IT', 'Information Technology'), ('Cybersecurity', 'Cybersecurity'), ('Data Analysis', 'Data Analysis'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('UI/UX Design', 'UI/UX Design'), ('Project Management', 'Project Management'), ('Product Management', 'Product Management'), ('Business Analysis', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('DevOps', 'DevOps'), ('Cloud Computing', 'Cloud Computing'), ('Networking', 'Networking'), ('Database Administration', 'Database Administration'), ('Technical Support', 'Technical Support'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Legal', 'Legal'), ('Customer Service', 'Customer Service')], max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('vacancy', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('salary_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('salary_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('job_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('job_location', models.CharField(max_length=255)),
                ('job_details', models.TextField()),
                ('job_requirements', models.TextField()),
                ('job_expiry_date', models.DateTimeField()),
                ('job_nature', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Hybrid', 'Hybrid'), ('Remotely', 'Remotely')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
