# Generated by Django 6.0.2 on 2026-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_choices',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('IT', 'Information Technology'), ('Cybersecurity', 'Cybersecurity'), ('Data Analysis', 'Data Analysis'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('UI/UX Design', 'UI/UX Design'), ('Business Analysis', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('DevOps', 'DevOps'), ('Cloud Computing', 'Cloud Computing'), ('Networking', 'Networking'), ('Database Administration', 'Database Administration'), ('Technical Support', 'Technical Support')], max_length=100),
        ),
    ]
